project:
  type: website
  resources:
    - "data/*csv"
format:
  dashboard:
    nav-buttons:
      - icon: github
        href: https://github.com/polarwatch/
  html:
    theme:
      - style/custom.scss
    css: style.css

execute:
  cache: false

