project:
  type: website
format:
  dashboard:
    nav-buttons:
      - icon: github
        href: https://github.com/polarwatch/
  html:
    theme:
      - custom.scss
    css: style.css

execute:
  cache: false

